openapi: 3.0.2
info:
  title: SW API
  contact:
    name: BBerry
  version: 0.1.0
paths:
  /sequence/{seq_id}/image/:
    get:
      tags:
        - image
        - image
      summary: List Images
      operationId: list_images_sequence__seq_id__image__get
      parameters:
        - required: true
          schema:
            title: Seq Id
            type: string
          name: seq_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response List Images Sequence  Seq Id  Image  Get
                anyOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/Image'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
        - image
        - image
      summary: Create Image
      operationId: create_image_sequence__seq_id__image__post
      parameters:
        - required: true
          schema:
            title: Seq Id
            type: string
          name: seq_id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateImageRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Create Image Sequence  Seq Id  Image  Post
                anyOf:
                  - $ref: '#/components/schemas/Image'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /sequence/{seq_id}/image/{img_id}:
    get:
      tags:
        - image
        - image
      summary: Get Image By Id
      operationId: get_image_by_id_sequence__seq_id__image__img_id__get
      parameters:
        - required: true
          schema:
            title: Seq Id
            type: string
          name: seq_id
          in: path
        - required: true
          schema:
            title: Img Id
            type: string
          name: img_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Image By Id Sequence  Seq Id  Image  Img Id  Get
                anyOf:
                  - $ref: '#/components/schemas/Image'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /sequence/{seq_id}:
    get:
      tags:
        - sequence
        - sequence
      summary: Get Sequence
      operationId: get_sequence_sequence__seq_id__get
      parameters:
        - required: true
          schema:
            title: Seq Id
            type: string
          name: seq_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Sequence Sequence  Seq Id  Get
                anyOf:
                  - $ref: '#/components/schemas/Sequence'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /sequence/:
    post:
      tags:
        - sequence
        - sequence
      summary: Create Sequence
      operationId: create_sequence_sequence__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSequenceRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Create Sequence Sequence  Post
                anyOf:
                  - $ref: '#/components/schemas/Sequence'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /detect/{seq_id}:
    post:
      tags:
        - detect
        - detect
      summary: Detect Sequence
      operationId: detect_sequence_detect__seq_id__post
      parameters:
        - required: true
          schema:
            title: Seq Id
            type: string
          name: seq_id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectSequenceRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Detect Sequence Detect  Seq Id  Post
                anyOf:
                  - $ref: '#/components/schemas/DetectSequenceResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CreateImageRequest:
      title: CreateImageRequest
      required:
        - img_bytes_base64
        - order
      type: object
      properties:
        img_bytes_base64:
          title: Img Bytes Base64
          type: string
        name:
          title: Name
          type: string
        order:
          title: Order
          type: integer
      example:
        img_bytes_base64: iVBORw0KGgoAAAANSUhEUgAAAC0AAAAeCAYAAAC49JeZAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAArzSURBVFhHjVhpU5vXFX4QAiEkxCb2xQbZbLaxje3Yddy4qTOZTNsP6af2Q39Af0Y+djr9De2XznQmM2mWpnGbuHG8JdjGYAMGDAbMjsQqsUmIpc9zpBewY5I89oV3Ofeec889y/OS8fBvv9/FK8jgk4z09avY3ZU432ZkYPcQqQy+c34714Lmpua/DnqXvjQ49/rBcUBVxoO//m734MJCBqU3N7exHt/E2noCm1vb2OEzSWmhLHcmfN5s5HJ4czx7xjvrSFZyGrrWBX8SKUkX5Vyu1IY0ZWdHcjt8u8PrXWzzwQ6Hy+WyuZIVNC8z07VvtD3myuH5GPpHZvBsNIyVtQS2t7mAFKdhcprMhTzZWaitKERLqAL1NSVwZ7nNgI+/6sTk7CKS29vY4oYzqVyGyAhtuCjfh8ttIYRqg1iMruPGt/2YnYuZ7Bb1mSFpR7hpZHZWJkqDAVy71IiiAh+4lRQS9Gz74xF8fOMxHnSP2WJJLuLKzERewI+SsiDKKkpRUFSALBqrxdc2Ehjg5r6404t/3+rBwmKMqnawkdi0U9re3qVn3NTvSv02PVtYWY9jm2snKNPeNYyJmSVs8FpramOSzaReDTre1mmoLUVRnhcu3puntdB3ncPoHZrG+sam7bOgMB/HGuvR0HwcpeUlyKahOhEpW16O4sXwGPp7BzE7Heai9CY9Ul1WgKtvNODTG08QW4vj4pvnceFnbWasMDYygfv3OrAwP4/LZ0LYpfcf9U+YTn+ej7Ln0HKqaS8cFCpPu/vRfrsdzfVlnFOPPF8O3IqZnmeT6BuZpec24Xa7EWqow+W3LtLoEIqDhcjx5uzFq5BMJtF8ohGtZ0/i4XedePyoGyuxVUyGl+m5UcQ3kyZfWV2B85f2jc7KzkZvdx8i4V1MR5axsLxmBmdlZeEU17r23lVU11bt6RoeGrV1t+iUHE8WQ8tFcxnjs4zhp0MzWFmNW0yeaG3Cr3/7nnmpurYS3lzvSwYLUhIsLcaJ08341fvv4srbl5FfELD4nwwvWWz+GKYjUSzF1m3t400hXPnFJVRUle/pmuEJ3r35HU/zGfxeDxM+m3mRyi3X8xcR27FwtL4WV9+5Qi82mLHCxkYcQwPD+OarO7hx/Rt0PXyCpcVle6dTkSLNOXvhNDweTyqW04sfBnlrI5G066qaitSpNtTbekJ0OYYHDKNO6lpfW+eaSURjG5bkgmtkYt4STjHc9sYZNJ9sRLYn217Ozy3g6//ewod//yc+//g/uP7pl/joH5/hkw8/x8jQC5ORZ0rLSix2temfChmupL545QLOnD9lISjE4wk87uhG+92HiC5FrfLUVRfjdGM1cultGe6KsawJtXU1Fqe5vly7T03uwc0vb5un58LztomJsUlLplv/u4vpyRmTVRKGjteh+VQjvGnlPwYZ2Xah1cIwL5Bnz1Sbnz0dxJ2b3yI8E7aiV1majzM0uCg/1zZqMa3KIc/Wh46ikkflYGp8Ct2dPZiPLNh9gFmriTJwY30DvY/7LFEcKJxqjlShuKQo/eRwaI0mhuDlty6hpDSYfgqMsiLd/voeq8y4baCQ+k43VKGmtCDVpdPDpaIf4E6DZcXIYXdzMD01iyl6UjsrDHjxDgv7+2+fwvHaEguJpcUlW1zx56C4pJgJum/EYag5WoM3r17EEZ6udT1CpVOJ19fzjN04CS/z42SoEsfYtJzk3PM0f8LP5pGX57cXgl7EllcQi65wAnCMhb2+OogSxv2ZxhrrUKoUOoWlhaX0LKCouJCjIH33ekhGIXGitXkvd7RxhZyTeFlMyKa6UrTUl1tHdIx1oAZjHnYSQUhyp2tra/bbShJ3m+nKtHflxQHkppWtM0w0HKhB+Ll5xzOvIpch1HbhDM5fPAuf32fPtHlrIOnE09yjlYUWFrk5WS8Z68DORnXXKTdCgm1YLVYTtEhhIJUEijMV+FxvlsmpyWwlt+xaUNvNZgPR79dBzaa17YTVeAfqfnJOgokvHbq3/KHOw2BGZ1DQiS3BMdCBm4bv0CO7qr98507L6v5VT2itNNf5Hnz+XKsUB3XZSbK5KDHV3KxBsVtGFlZMlziF6TkwbLb4hPiDAzeZ2J7nOUntXTxBi2hSIu1dkSkXY+4gUpvb3/BPgbjNuUtnWX2q7X6eza6L1CKZpE1m+MvDNOqYNRx4GOOKP3mEZiJM9ibv7ZLzricSWCXHFkSiFA4OlPXxeJynxMV/AKr1fT0DluiCHNTUchzn2NwcOjBGajswFjb99o/G6h+tMF6dSqi1/YRSTPrycll7c8yAPvLrxKbY3w5Gpxfo6dSp6KhVeRxEyf6iSzFTcBhURm9+eQf/+ug6Bvuf78kqMUUFxPK0iVU2vW6yzshilDZskaJuUXbbbKDRGVjhjmPR/XorqDQVcgiTJDePBibxYnoRj/p4bAwnebmiqgzBA81kcX6JtHMxffd9zEXmcffrb9HR3mldtuN+F6YmUl1VKK8sxTlWFhE1bWWOYfJ4cBqbDEflmDMYki6srqzZ5GWWHAdHyCPUmrXrOLvm/d5xfHrrKSJLq/a+nERJMiJJDiLhOTPsMKiujzx/YXVZ4djPEHnCrqvaLEiXuI84UCA/z8JkfGYZw+MLVpv3Ri55qpJw5PkoxkcnbLIgT4sENTQfs8VS326poywOFuESiU4Ds96BPDzCtn5w469CMb/JMBNUYGR814MnL9EB1fq2N06b8QrTFeZP9/AsFsnyBIVT5rWzJR9EVxPYYEx7yKJUS30kTUrC/PwAj6zM2nwO41vGNrQcw89/edm8IWYoqFZ3dTzBvVv395JLYacypuEgPBPBAAmRqK1HXZVHvbqybsZV8uRksCD9XICtfdY2FmcOKSyqSwNscsy5P1wLfTC7sGrfdbHYilUOfQvqt+pmIdtyFWMsRL7bwg+Ek2y/CpuDzGygb5AU9radlBJbufVjRhfwe09ycepVeAZYNapqK+xUVUZVRcTlpyamEee3qPi3n02tmCTKVUvqV1niN88qkW7/7x5u3bi7x+7khULyXpGbutAR8/zL3LcH1z/7CsODIxZm6mbiCz8EbagymEf2FkjpJX/pfPAYo8/H0hKqTH47zcaWBnOE5Ov45S9k/vE3jR9ks5lE+SGqJqJdz5LLRsifVXPlca9XNVtRmIJkhp4N4x5ZmbivPnLV+r2sKM1Hgogw6xX+h3l6mWVMBh8juVcjMb38FhSBEj1WjxDUQXUcHe1d9qVeWuhDgZ/fq7f/8i6b3C6GJhfROzKHabZPJZ2qgkJDfFfMTR8H8pCSSfV4jiexwI8CbUAF38d8aKgpwsm6EnzR/hwLsbh9SlVWV5oBggjRJI97ezOBK601aKoNomNgGl1DYeuySv6qmtR3qQOV4sH+IYRIot48VbNvtF6qMkxEYjR+AdPzrNvrm2a8DFWcKb51rZa/tZW0cqRj8/C5PHC0PJ8Lc3NkZp/cGcQU1zgMAZ8Hb7XWop6GLPOD+m7POF7Mxiw/Xgd1wPJiP94+ewRBxnTGN39+J1XH0ljlUYWX1szwRXprdYOtmV7Y0nnzv6LEw3Dy0rh8vwcVRT6UF/nJyrz2VyeVpCfDc2bMio6dmxf/1p8VFD7+3Gzk0+gQ4zOYn6oWY2GewFyMjkpYidtktZBRCklVmWC+FznZbjqmgLp8NPpP16gm1dUPQiGT3NqxBawTHRBILeY2murmSP9RbQ86kVdh3CE9KJGe8305ISVzGID/A/NIzY5oSvf6AAAAAElFTkSuQmCC
        name: Sample Image Name
        order: 0
    CreateSequenceRequest:
      title: CreateSequenceRequest
      required:
        - seq_name
      type: object
      properties:
        seq_name:
          title: Seq Name
          type: string
      example:
        seq_name: Sample Sequence Name
    DetectSequenceRequest:
      title: DetectSequenceRequest
      required:
        - img_bytes_base64
      type: object
      properties:
        img_bytes_base64:
          title: Img Bytes Base64
          type: string
      example:
        img_bytes_base64: iVBORw0KGgoAAAANSUhEUgAAAC0AAAAeCAYAAAC49JeZAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAArzSURBVFhHjVhpU5vXFX4QAiEkxCb2xQbZbLaxje3Yddy4qTOZTNsP6af2Q39Af0Y+djr9De2XznQmM2mWpnGbuHG8JdjGYAMGDAbMjsQqsUmIpc9zpBewY5I89oV3Ofeec889y/OS8fBvv9/FK8jgk4z09avY3ZU432ZkYPcQqQy+c34714Lmpua/DnqXvjQ49/rBcUBVxoO//m734MJCBqU3N7exHt/E2noCm1vb2OEzSWmhLHcmfN5s5HJ4czx7xjvrSFZyGrrWBX8SKUkX5Vyu1IY0ZWdHcjt8u8PrXWzzwQ6Hy+WyuZIVNC8z07VvtD3myuH5GPpHZvBsNIyVtQS2t7mAFKdhcprMhTzZWaitKERLqAL1NSVwZ7nNgI+/6sTk7CKS29vY4oYzqVyGyAhtuCjfh8ttIYRqg1iMruPGt/2YnYuZ7Bb1mSFpR7hpZHZWJkqDAVy71IiiAh+4lRQS9Gz74xF8fOMxHnSP2WJJLuLKzERewI+SsiDKKkpRUFSALBqrxdc2Ehjg5r6404t/3+rBwmKMqnawkdi0U9re3qVn3NTvSv02PVtYWY9jm2snKNPeNYyJmSVs8FpramOSzaReDTre1mmoLUVRnhcu3puntdB3ncPoHZrG+sam7bOgMB/HGuvR0HwcpeUlyKahOhEpW16O4sXwGPp7BzE7Heai9CY9Ul1WgKtvNODTG08QW4vj4pvnceFnbWasMDYygfv3OrAwP4/LZ0LYpfcf9U+YTn+ej7Ln0HKqaS8cFCpPu/vRfrsdzfVlnFOPPF8O3IqZnmeT6BuZpec24Xa7EWqow+W3LtLoEIqDhcjx5uzFq5BMJtF8ohGtZ0/i4XedePyoGyuxVUyGl+m5UcQ3kyZfWV2B85f2jc7KzkZvdx8i4V1MR5axsLxmBmdlZeEU17r23lVU11bt6RoeGrV1t+iUHE8WQ8tFcxnjs4zhp0MzWFmNW0yeaG3Cr3/7nnmpurYS3lzvSwYLUhIsLcaJ08341fvv4srbl5FfELD4nwwvWWz+GKYjUSzF1m3t400hXPnFJVRUle/pmuEJ3r35HU/zGfxeDxM+m3mRyi3X8xcR27FwtL4WV9+5Qi82mLHCxkYcQwPD+OarO7hx/Rt0PXyCpcVle6dTkSLNOXvhNDweTyqW04sfBnlrI5G066qaitSpNtTbekJ0OYYHDKNO6lpfW+eaSURjG5bkgmtkYt4STjHc9sYZNJ9sRLYn217Ozy3g6//ewod//yc+//g/uP7pl/joH5/hkw8/x8jQC5ORZ0rLSix2temfChmupL545QLOnD9lISjE4wk87uhG+92HiC5FrfLUVRfjdGM1cultGe6KsawJtXU1Fqe5vly7T03uwc0vb5un58LztomJsUlLplv/u4vpyRmTVRKGjteh+VQjvGnlPwYZ2Xah1cIwL5Bnz1Sbnz0dxJ2b3yI8E7aiV1majzM0uCg/1zZqMa3KIc/Wh46ikkflYGp8Ct2dPZiPLNh9gFmriTJwY30DvY/7LFEcKJxqjlShuKQo/eRwaI0mhuDlty6hpDSYfgqMsiLd/voeq8y4baCQ+k43VKGmtCDVpdPDpaIf4E6DZcXIYXdzMD01iyl6UjsrDHjxDgv7+2+fwvHaEguJpcUlW1zx56C4pJgJum/EYag5WoM3r17EEZ6udT1CpVOJ19fzjN04CS/z42SoEsfYtJzk3PM0f8LP5pGX57cXgl7EllcQi65wAnCMhb2+OogSxv2ZxhrrUKoUOoWlhaX0LKCouJCjIH33ekhGIXGitXkvd7RxhZyTeFlMyKa6UrTUl1tHdIx1oAZjHnYSQUhyp2tra/bbShJ3m+nKtHflxQHkppWtM0w0HKhB+Ll5xzOvIpch1HbhDM5fPAuf32fPtHlrIOnE09yjlYUWFrk5WS8Z68DORnXXKTdCgm1YLVYTtEhhIJUEijMV+FxvlsmpyWwlt+xaUNvNZgPR79dBzaa17YTVeAfqfnJOgokvHbq3/KHOw2BGZ1DQiS3BMdCBm4bv0CO7qr98507L6v5VT2itNNf5Hnz+XKsUB3XZSbK5KDHV3KxBsVtGFlZMlziF6TkwbLb4hPiDAzeZ2J7nOUntXTxBi2hSIu1dkSkXY+4gUpvb3/BPgbjNuUtnWX2q7X6eza6L1CKZpE1m+MvDNOqYNRx4GOOKP3mEZiJM9ibv7ZLzricSWCXHFkSiFA4OlPXxeJynxMV/AKr1fT0DluiCHNTUchzn2NwcOjBGajswFjb99o/G6h+tMF6dSqi1/YRSTPrycll7c8yAPvLrxKbY3w5Gpxfo6dSp6KhVeRxEyf6iSzFTcBhURm9+eQf/+ug6Bvuf78kqMUUFxPK0iVU2vW6yzshilDZskaJuUXbbbKDRGVjhjmPR/XorqDQVcgiTJDePBibxYnoRj/p4bAwnebmiqgzBA81kcX6JtHMxffd9zEXmcffrb9HR3mldtuN+F6YmUl1VKK8sxTlWFhE1bWWOYfJ4cBqbDEflmDMYki6srqzZ5GWWHAdHyCPUmrXrOLvm/d5xfHrrKSJLq/a+nERJMiJJDiLhOTPsMKiujzx/YXVZ4djPEHnCrqvaLEiXuI84UCA/z8JkfGYZw+MLVpv3Ri55qpJw5PkoxkcnbLIgT4sENTQfs8VS326poywOFuESiU4Ds96BPDzCtn5w469CMb/JMBNUYGR814MnL9EB1fq2N06b8QrTFeZP9/AsFsnyBIVT5rWzJR9EVxPYYEx7yKJUS30kTUrC/PwAj6zM2nwO41vGNrQcw89/edm8IWYoqFZ3dTzBvVv395JLYacypuEgPBPBAAmRqK1HXZVHvbqybsZV8uRksCD9XICtfdY2FmcOKSyqSwNscsy5P1wLfTC7sGrfdbHYilUOfQvqt+pmIdtyFWMsRL7bwg+Ek2y/CpuDzGygb5AU9radlBJbufVjRhfwe09ycepVeAZYNapqK+xUVUZVRcTlpyamEee3qPi3n02tmCTKVUvqV1niN88qkW7/7x5u3bi7x+7khULyXpGbutAR8/zL3LcH1z/7CsODIxZm6mbiCz8EbagymEf2FkjpJX/pfPAYo8/H0hKqTH47zcaWBnOE5Ov45S9k/vE3jR9ks5lE+SGqJqJdz5LLRsifVXPlca9XNVtRmIJkhp4N4x5ZmbivPnLV+r2sKM1Hgogw6xX+h3l6mWVMBh8juVcjMb38FhSBEj1WjxDUQXUcHe1d9qVeWuhDgZ/fq7f/8i6b3C6GJhfROzKHabZPJZ2qgkJDfFfMTR8H8pCSSfV4jiexwI8CbUAF38d8aKgpwsm6EnzR/hwLsbh9SlVWV5oBggjRJI97ezOBK601aKoNomNgGl1DYeuySv6qmtR3qQOV4sH+IYRIot48VbNvtF6qMkxEYjR+AdPzrNvrm2a8DFWcKb51rZa/tZW0cqRj8/C5PHC0PJ8Lc3NkZp/cGcQU1zgMAZ8Hb7XWop6GLPOD+m7POF7Mxiw/Xgd1wPJiP94+ewRBxnTGN39+J1XH0ljlUYWX1szwRXprdYOtmV7Y0nnzv6LEw3Dy0rh8vwcVRT6UF/nJyrz2VyeVpCfDc2bMio6dmxf/1p8VFD7+3Gzk0+gQ4zOYn6oWY2GewFyMjkpYidtktZBRCklVmWC+FznZbjqmgLp8NPpP16gm1dUPQiGT3NqxBawTHRBILeY2murmSP9RbQ86kVdh3CE9KJGe8305ISVzGID/A/NIzY5oSvf6AAAAAElFTkSuQmCC
    DetectSequenceResponse:
      title: DetectSequenceResponse
      type: object
      properties:
        detection_results:
          title: Detection Results
          type: array
          items:
            $ref: '#/components/schemas/DetectionResult'
          default: []
      example:
        detection_results:
          - image_id: 0ca59e1e-7dc6-4990-ae36-86aeb0ee18c7
            image_name: Sample Image Name
            confidence: 0.98
            x: 512
            'y': 256
    DetectionResult:
      title: DetectionResult
      required:
        - image_id
        - image_name
        - confidence
        - x
        - 'y'
      type: object
      properties:
        image_id:
          title: Image Id
          type: string
        image_name:
          title: Image Name
          type: string
        confidence:
          title: Confidence
          type: number
        x:
          title: X
          type: number
        'y':
          title: 'Y'
          type: number
      example:
        image_id: 0ca59e1e-7dc6-4990-ae36-86aeb0ee18c7
        image_name: Sample Image Name
        confidence: 0.98
        x: 512
        'y': 256
    GenericErrorResponse:
      title: GenericErrorResponse
      required:
        - error
      type: object
      properties:
        error:
          title: Error
          type: string
      example:
        error: Sample Error Message
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Image:
      title: Image
      required:
        - img_bytes
        - order
      type: object
      properties:
        img_id:
          title: Img Id
          type: string
        img_bytes:
          title: Img Bytes
          type: string
          format: binary
        name:
          title: Name
          type: string
        order:
          title: Order
          type: integer
        seq_id:
          title: Seq Id
          type: string
      example:
        img_id: 0ca59e1e-7dc6-4990-ae36-86aeb0ee18c7
        img_bytes: iVBORw0KGgoAAAANSUhEUgAAAC0AAAAeCAYAAAC49JeZAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAArzSURBVFhHjVhpU5vXFX4QAiEkxCb2xQbZbLaxje3Yddy4qTOZTNsP6af2Q39Af0Y+djr9De2XznQmM2mWpnGbuHG8JdjGYAMGDAbMjsQqsUmIpc9zpBewY5I89oV3Ofeec889y/OS8fBvv9/FK8jgk4z09avY3ZU432ZkYPcQqQy+c34714Lmpua/DnqXvjQ49/rBcUBVxoO//m734MJCBqU3N7exHt/E2noCm1vb2OEzSWmhLHcmfN5s5HJ4czx7xjvrSFZyGrrWBX8SKUkX5Vyu1IY0ZWdHcjt8u8PrXWzzwQ6Hy+WyuZIVNC8z07VvtD3myuH5GPpHZvBsNIyVtQS2t7mAFKdhcprMhTzZWaitKERLqAL1NSVwZ7nNgI+/6sTk7CKS29vY4oYzqVyGyAhtuCjfh8ttIYRqg1iMruPGt/2YnYuZ7Bb1mSFpR7hpZHZWJkqDAVy71IiiAh+4lRQS9Gz74xF8fOMxHnSP2WJJLuLKzERewI+SsiDKKkpRUFSALBqrxdc2Ehjg5r6404t/3+rBwmKMqnawkdi0U9re3qVn3NTvSv02PVtYWY9jm2snKNPeNYyJmSVs8FpramOSzaReDTre1mmoLUVRnhcu3puntdB3ncPoHZrG+sam7bOgMB/HGuvR0HwcpeUlyKahOhEpW16O4sXwGPp7BzE7Heai9CY9Ul1WgKtvNODTG08QW4vj4pvnceFnbWasMDYygfv3OrAwP4/LZ0LYpfcf9U+YTn+ej7Ln0HKqaS8cFCpPu/vRfrsdzfVlnFOPPF8O3IqZnmeT6BuZpec24Xa7EWqow+W3LtLoEIqDhcjx5uzFq5BMJtF8ohGtZ0/i4XedePyoGyuxVUyGl+m5UcQ3kyZfWV2B85f2jc7KzkZvdx8i4V1MR5axsLxmBmdlZeEU17r23lVU11bt6RoeGrV1t+iUHE8WQ8tFcxnjs4zhp0MzWFmNW0yeaG3Cr3/7nnmpurYS3lzvSwYLUhIsLcaJ08341fvv4srbl5FfELD4nwwvWWz+GKYjUSzF1m3t400hXPnFJVRUle/pmuEJ3r35HU/zGfxeDxM+m3mRyi3X8xcR27FwtL4WV9+5Qi82mLHCxkYcQwPD+OarO7hx/Rt0PXyCpcVle6dTkSLNOXvhNDweTyqW04sfBnlrI5G066qaitSpNtTbekJ0OYYHDKNO6lpfW+eaSURjG5bkgmtkYt4STjHc9sYZNJ9sRLYn217Ozy3g6//ewod//yc+//g/uP7pl/joH5/hkw8/x8jQC5ORZ0rLSix2temfChmupL545QLOnD9lISjE4wk87uhG+92HiC5FrfLUVRfjdGM1cultGe6KsawJtXU1Fqe5vly7T03uwc0vb5un58LztomJsUlLplv/u4vpyRmTVRKGjteh+VQjvGnlPwYZ2Xah1cIwL5Bnz1Sbnz0dxJ2b3yI8E7aiV1majzM0uCg/1zZqMa3KIc/Wh46ikkflYGp8Ct2dPZiPLNh9gFmriTJwY30DvY/7LFEcKJxqjlShuKQo/eRwaI0mhuDlty6hpDSYfgqMsiLd/voeq8y4baCQ+k43VKGmtCDVpdPDpaIf4E6DZcXIYXdzMD01iyl6UjsrDHjxDgv7+2+fwvHaEguJpcUlW1zx56C4pJgJum/EYag5WoM3r17EEZ6udT1CpVOJ19fzjN04CS/z42SoEsfYtJzk3PM0f8LP5pGX57cXgl7EllcQi65wAnCMhb2+OogSxv2ZxhrrUKoUOoWlhaX0LKCouJCjIH33ekhGIXGitXkvd7RxhZyTeFlMyKa6UrTUl1tHdIx1oAZjHnYSQUhyp2tra/bbShJ3m+nKtHflxQHkppWtM0w0HKhB+Ll5xzOvIpch1HbhDM5fPAuf32fPtHlrIOnE09yjlYUWFrk5WS8Z68DORnXXKTdCgm1YLVYTtEhhIJUEijMV+FxvlsmpyWwlt+xaUNvNZgPR79dBzaa17YTVeAfqfnJOgokvHbq3/KHOw2BGZ1DQiS3BMdCBm4bv0CO7qr98507L6v5VT2itNNf5Hnz+XKsUB3XZSbK5KDHV3KxBsVtGFlZMlziF6TkwbLb4hPiDAzeZ2J7nOUntXTxBi2hSIu1dkSkXY+4gUpvb3/BPgbjNuUtnWX2q7X6eza6L1CKZpE1m+MvDNOqYNRx4GOOKP3mEZiJM9ibv7ZLzricSWCXHFkSiFA4OlPXxeJynxMV/AKr1fT0DluiCHNTUchzn2NwcOjBGajswFjb99o/G6h+tMF6dSqi1/YRSTPrycll7c8yAPvLrxKbY3w5Gpxfo6dSp6KhVeRxEyf6iSzFTcBhURm9+eQf/+ug6Bvuf78kqMUUFxPK0iVU2vW6yzshilDZskaJuUXbbbKDRGVjhjmPR/XorqDQVcgiTJDePBibxYnoRj/p4bAwnebmiqgzBA81kcX6JtHMxffd9zEXmcffrb9HR3mldtuN+F6YmUl1VKK8sxTlWFhE1bWWOYfJ4cBqbDEflmDMYki6srqzZ5GWWHAdHyCPUmrXrOLvm/d5xfHrrKSJLq/a+nERJMiJJDiLhOTPsMKiujzx/YXVZ4djPEHnCrqvaLEiXuI84UCA/z8JkfGYZw+MLVpv3Ri55qpJw5PkoxkcnbLIgT4sENTQfs8VS326poywOFuESiU4Ds96BPDzCtn5w469CMb/JMBNUYGR814MnL9EB1fq2N06b8QrTFeZP9/AsFsnyBIVT5rWzJR9EVxPYYEx7yKJUS30kTUrC/PwAj6zM2nwO41vGNrQcw89/edm8IWYoqFZ3dTzBvVv395JLYacypuEgPBPBAAmRqK1HXZVHvbqybsZV8uRksCD9XICtfdY2FmcOKSyqSwNscsy5P1wLfTC7sGrfdbHYilUOfQvqt+pmIdtyFWMsRL7bwg+Ek2y/CpuDzGygb5AU9radlBJbufVjRhfwe09ycepVeAZYNapqK+xUVUZVRcTlpyamEee3qPi3n02tmCTKVUvqV1niN88qkW7/7x5u3bi7x+7khULyXpGbutAR8/zL3LcH1z/7CsODIxZm6mbiCz8EbagymEf2FkjpJX/pfPAYo8/H0hKqTH47zcaWBnOE5Ov45S9k/vE3jR9ks5lE+SGqJqJdz5LLRsifVXPlca9XNVtRmIJkhp4N4x5ZmbivPnLV+r2sKM1Hgogw6xX+h3l6mWVMBh8juVcjMb38FhSBEj1WjxDUQXUcHe1d9qVeWuhDgZ/fq7f/8i6b3C6GJhfROzKHabZPJZ2qgkJDfFfMTR8H8pCSSfV4jiexwI8CbUAF38d8aKgpwsm6EnzR/hwLsbh9SlVWV5oBggjRJI97ezOBK601aKoNomNgGl1DYeuySv6qmtR3qQOV4sH+IYRIot48VbNvtF6qMkxEYjR+AdPzrNvrm2a8DFWcKb51rZa/tZW0cqRj8/C5PHC0PJ8Lc3NkZp/cGcQU1zgMAZ8Hb7XWop6GLPOD+m7POF7Mxiw/Xgd1wPJiP94+ewRBxnTGN39+J1XH0ljlUYWX1szwRXprdYOtmV7Y0nnzv6LEw3Dy0rh8vwcVRT6UF/nJyrz2VyeVpCfDc2bMio6dmxf/1p8VFD7+3Gzk0+gQ4zOYn6oWY2GewFyMjkpYidtktZBRCklVmWC+FznZbjqmgLp8NPpP16gm1dUPQiGT3NqxBawTHRBILeY2murmSP9RbQ86kVdh3CE9KJGe8305ISVzGID/A/NIzY5oSvf6AAAAAElFTkSuQmCC
        name: Sample Image Name
        order: 0
        seq_id: 3f2b9c96-9fb9-477c-adc4-270e1e331df3
    Metrics:
      title: Metrics
      required:
        - seq_id
        - last_computed
        - runs
        - avg_run_duration
      type: object
      properties:
        seq_id:
          title: Seq Id
          type: string
        last_computed:
          title: Last Computed
          type: integer
        runs:
          title: Runs
          type: integer
        avg_run_duration:
          title: Avg Run Duration
          type: number
      example:
        seq_id: 3f2b9c96-9fb9-477c-adc4-270e1e331df3
        last_computed: 1657165172
        runs: 10
        avg_run_duration: 60
    Sequence:
      title: Sequence
      required:
        - seq_name
      type: object
      properties:
        seq_id:
          title: Seq Id
          type: string
        seq_name:
          title: Seq Name
          type: string
        metrics:
          $ref: '#/components/schemas/Metrics'
      example:
        seq_id: 3f2b9c96-9fb9-477c-adc4-270e1e331df3
        seq_name: Sample Sequence Name
        metrics:
          seq_id: 3f2b9c96-9fb9-477c-adc4-270e1e331df3
          last_computed: 1657165172
          runs: 10
          avg_run_duration: 60
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
